"""users table

Revision ID: 43c8554a5ad9
Revises: c48d4858dfed
Create Date: 2020-01-12 03:00:04.833431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43c8554a5ad9'
down_revision = 'c48d4858dfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('user', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'result_no_stop_words')
    op.drop_column('user', 'result_all')
    # ### end Alembic commands ###
